const TITLES = [
  "Warhammer 40k - Still Even More Imotekh the Stormlord comics & memes",
  "TV Shows funny moments",
  "Brits and the C word",
  "Feel happy and depressed at the same time",
  "Apologies to Mr Puzo.",
  "Evening Voidling album",
  "Smudge Smudging Smudgingly",
  "Get it, Gram Gram!",
  "ICM QUALITY MIX - Vol.52 RED ALL OVER",
  "Best part is Pepsi has become quite the bed snuggler! I've taken a little nap with her the last two days after work (my back needs it). She curls up right on my chest and purrs like a V-8.",
  "Misato cosplay (Evangelion)",
  "You want to be the girl right?",
  "Jesus, dude.  Who are you tryna fight?!",
  "...",
  "I feel this in my soul.",
  "Aw, how cute!",
  "More Naps with Waffles",
  "24 nice and wholesome things to brighten your day, vol 278",
  "It's wimdy!",
  "This is a post about memes",
  "More Hunter Biden redemption arc really politely educating people. It's crazy awesome. More of this energy.",
  "Just Scoots",
  "I have to LEAVE",
  "Froggy Friday",
  "Ok but stop it",
  "I was thinking we were gonna snuggle",
  "Risotto is still waiting for the cat like reflexes to kick in",
  "Here's Sally.",
  "“I’m a Wizard, Mother!”",
  "Chill Painting Day! Let's climb some mountains!! -Flooko",
  "Schitz & Giggles 034",
  "Treats? Please?",
  "Overpass sign.",
  "Frank is being Awesome :)",
  "Zach...outtakes",
  "Sad news",
  "Making Friends With Neurodivergent Platypi",
  "Frenchies are so dramatic",
  'Cohn: "It is bad for your wallet, bad for your health, but good for [Trump\'s] friends." – Jonathan Cohn breaks down why this new $700M deal to build new coal plants and spruce up old ones is a quintessential Trump move.',
  "What will you tell them?",
  "Do fucking better!",
  "Everyone got a really good bath",
  "Carefully Curated Crap, Vol. 865",
  "Faith",
  "I feel comfortable leaving to go have dinner",
  "Goals of Christian Nationalists",
  "This place needs more Puffins",
  "Its Friday!",
  "Parliamentary democracy in New Zealand is......different.",
  "Put some tonys on dat.",
  "Big or smol, Cat is CAT!",
  "June 5",
  "I’m trying to better myself!",
  "My favorite thing about being an artist is making things that I enjoy",
  "Jalapeno-Cheddar Cornbread!",
  "Nostalgia dump",
  "Flight is TOMORROW!",
  "The burger must be willing.",
  "Baby Corn Next to Thing",
  "Baby Corn Next to Things",
  "Dump #373",
  "Happy Pride! A few of my favorite stolen pics.",
  "Why? SkullJesus",
  "Nope, Nope, Nope, Nope, Nope, Nope, Nope.",
  "It’s going to come in steps",
  "That face really says it all",
  "Sometimes I Draw",
  "What did I just watch?",
  "One of my favorite Buffy and Giles moments.",
  "Happy Fri-Ray",
  "R.I.P. to the Legal Assassin",
  "I don't know",
  "Jorge has found his forever home!!",
  "Mr Feeny was cutoff on my first post and I couldn't leave him out.  They're Back for Mr Feeny Too!!!.",
  "Lynda Carter 1972",
  "I’m happy with their progress",
  "I forgot all about this fuuuuuck",
  "Me with few of my fans on Friday evening",
  "That person has a future as a police forensic artist.",
  "Toilet paper",
  "It had to be done",
  "The first week of pride",
  "Mistakes were made...",
  "I wouldn't be surprised if this guy is on a registry that says he isn't allowed to be a certain distance from a school",
  "Serie from Frieren is ready!",
  "We've been had",
  "Oi.",
  "I hurt just watching",
  "Fish dress in action.",
  "Everyone plays with their balls in the privacy of their own home.",
  "8 years as the Free Meal Lady.",
  "Marco Rubio lies to Congress about the President that never sleeps",
  "Brown bear easily floats while looking for sockeye salmon",
  "Installing skirt boards.",
  "R.I.P to a legend.",
  "The Idiots of Imgur: A Mini Dump pt 259",
  "Alcohol changes people",
  "Chuckle Dump",
  "They both got spayed and they’re comforting each other",
  "Always remember.",
  "Petah.... the horse is here...",
  "Let's not pretend this isn't a financial relationship",
  "I send not to know for whom the bell tolls",
  "THEY CAME BACK!!!! Yes this is a bit long but dammit it's worth the time. Good stuff for the soul. Plus all the Happy Dogs and People!!!",
  "SD cards were invented in 1999 Sony in 1998",
  "Day 278 of posting Calvin and Hobbes Comics every day.",
  "Robert Reich: Trump is losing it. Something shifted this week. He's become a loser, a lame duck president whose quack no longer causes anyone to quake.",
  "June (OC)",
  "Interesting Pics",
  "Harbor gives his humans a lecture when they came back from their vacation",
  "Danny DeVito’s answer after being asked why he’s so awesome: ‘I don’t know’",
  "It doesn't stop",
  "Proudly stolen, mostly funny",
  "Space Them",
  "Straight Pride - Fly your flag.",
  "Happy Pride month!",
  "Hyperlane Nomads - Page 106 & Happy Pride Month!",
  "Pumped. Started last night. Obviously still in progress, but I am finally doing a Cassowary.",
  "Spider breath!",
  "Godspeed ACLU",
  "Alan Tudyk and Brent Spiner talk about auditioning",
  "RIP Anthony Stewart Head",
  "Ren faire!",
  "Hanging out with your tall friend - by YuzuPyon & FearFiction",
  "I drew an antique diving helmet with charcoal - an art collector saw it at my framer's shop and bought it",
  "For all you degenerates out there",
  "The Ren Faire Part 3",
  "The Chosen One",
  "Dark souls 3 firekeeper cosplay by Keewah.Cos",
  "RIP Anthony",
  "Nobody fucks with The Jesus!",
  "Finally, some good news.",
  "Australian kitty.",
  "Happy Ferris Day",
  "Demons",
  "BY GOD, IT'S BERNIE SANDERS WITH THE STEEL CHAIR",
  "Republicans create dangerous conditions for trans people then deny them the right of self defense when the danger is realized.",
  "You're fast, i will catch you, eventually.",
  "I earned Madison snuggles tonight!",
  "Welcome to my Ted Talk, have a seat",
  "Algeria celebrating their football win",
  "Memes vol 696 Movies",
  'This is what\'s known as a "self burn"',
  "Companies are harming themselves by not supporting pride.",
  "There Always Someone at the Top of the Heap ...",
  "His watch is ended. RIP Anthony Head",
  "Fish net Friday",
  "retrieval, by huleeb",
  "Putin has reached Trump’s level with those numbers, then.",
  "BABY NO PLEASE",
  "Couldn't have said it better myself",
  "The greatest thing about finishing a good book is sharing it with someone else... you have 1,200 pages of homework, Son.",
  "F***ing men like you built the hydrogen bomb. Men like you thought it up. You think you're so creative.",
  "Keith Richards",
  "Republicans so badly want everyone to hate trans people. People are more concerned with being able to survive. Republicans hate working class people.",
  "Republicans are pedophiles",
  "Never seen such truth in a meme.",
  "comics i drew (real)",
  "Vibing and hopping at the volcano",
  "A little coffee stop in Wembley!",
  "Ruby is at COBB COUNTY ANIMAL SERVICES (1060 AL BISHOP DR, MARIETTA, GA)  (770) 499-4136",
  "Reach out to someone…",
  "Well I'll be damned...",
  "My latest cuff, made with labradorite stones. It's made entirely by wire wrapping, it took me about four hours.",
  "The Ren Faire Part 4",
  "Bad Gorilla, Chill",
  "Mini dump",
  "loader.zip",
  "The Savage....",
  "dude has no clue",
  "Tires decoded.",
  "Pink litho",
  "what's missing? (OC)",
  "Discovered a new dinosaur.",
  "Funcle is getting payback",
  "Not a drag queen",
  "Oh, The Hypocrisy",
  "A photo of my dog Panko every day",
  "Talarico vs Paxton",
  "Great elementary teachers deserve a gold star and a nap…",
  "Porch Pirates",
  "Cheese Please [OC]",
  "Lilac’s first bath",
  "Return of the Meme: 1708 (escaped containment)",
  "Well time for some adorableness.",
  "We don't love Stevie Wonder enough",
  "Friday Memes",
  "Albanian protesters rally against Jared Kushner resort backed by PM Edi Rama",
  '"Where was all this queer stuff when we were growing up?"',
  "Empirical Testing :)",
  "Wife of man too angry to die is ALSO too angry to die. They were made for each other.",
  "Madam Squeak is very opinionated",
  "Enjoy that morning Friday coffee!",
  "American Rights?",
  "Kenya Believe It!",
  "Chris Farley discusses his visit to congress",
  "The stupid can't think their way out of a red hat",
  "wImDY.",
  "My father, today is father's day. He died in 99' only 41 and now I'm older than he ever was. I still miss him",
  "Did he flip me off?",
  "night night",
  "Daily Dose of Winter Day 1329",
  "A moderately sized DK dump of stolen memes for these trying times 2097.",
  "Another qualified, patriotic young professional",
  "Memes vol 695",
  "I feel better during the day at least",
  "Lil bro is over it……..",
  "Dumps of Unusual Size 272: Artscapes, Part Three",
  "GovBrief Today #490",
  "A day in the life of a trucker (4 June, 2026)",
  "Going Up? [OC]",
  "Every third of his guests is gold.",
  "Short stack",
  "1964",
  "K-Pop Demon Hunters Incorrect Quotes for the 8th time",
  "VoidBois evening round-up",
  "Opposite Day",
  "a little watercolor that I made",
  "Talarico",
  "Have a Tree-mendous day! Shadow and Chance",
  "How cute they are",
  "DREAM TEAM SUPREME ~ Suction",
  "DREAM TEAM SUPREME ~ Foot",
  "First rule of kitten fight club is too look ridiculously cute while fighting",
  "Art live on the wedding",
  "Incredible tie-dying skills",
  "They were finally grooming each other!",
  "Dad would be so proud",
  "New fun thing arrived today! Two of our birds tried it… but our Senegal parrot was not a fan.",
  "Dinner time for the babies",
  "Babies Garbonzo, Bean, and Rooster are growing up... And more babies are born.",
  "4 more Choplets need a home",
  "A photo of my pup Tiger Lilly #1259",
  "Finally finished! This is my best character sheet so far. I'm happy with the results. :) #fanart #starwars #digitalartㅤㅤㅤㅤ",
  "Behind all the glamor",
  "Pole Chaos!",
  "Sometimes you just gotta embrace the absurd",
  "The prophecy",
  "It's dangerous for ANYONE to have this much money",
  "And the Oscar goes to?",
  "I grew a pair",
  "Republicans again blocked Sen. Ossoff's amendment to prevent insurance companies from denying or delaying needed care.",
  "“Mother, hush. I’m watching a documentary.”",
  "Buddy Gator - Animation",
  "Friends",
  "Furry Checkpoint >Suave<",
  "Nature moment a day 555 - Feeding me slowl",
  "Be gay, brick cops",
  "High Maintenance Husky",
  "Rejecting Data Centers like a Boss",
  "Not a pussysexual",
  "Not a dicksexual",
  "Most of the time it only takes one step to be a lesbian. It took me two.",
  "There's only two genders",
  "The sacrifices you make",
  "This place needs more Narwhals",
  "Don the Con, at it again.",
  "Mamdani Rules!",
  "Hands Off protest in Cincinnati, OH",
  "Keep it to yourself :)",
  "Annual reminder that Ronald Reagan is still dead.",
  "We're tired of Democratic leaders who are weak",
  "I wouldn't even be mad.",
  "June 4",
  "Thursday funnies and things",
  "I want this for late night snacks",
  "Deadlock Profiles // Day 1: Abrams",
  "Freaking Nandor",
  "Baby!",
  "Snoozy McSnoozeface",
  "Carefully Curated Crap, Vol. 864",
  "It's perfect",
  "Crumb being so sleepy that she's become a potato!",
  "This is what sportsmanship looks like. Right after an intense battle in the ring, Ukrainian legend Oleksandr Usyk didn't just celebrate his victory—he immediately lifted up a defeated Daniel Dubois.\"It’s boxing. It’s not ballet, it’s not dancing... You",
  "Just five minutes of Nadja",
  "It’s Comedy Gold 9",
  "How Hitler began",
  "It's hot to fix a car",
  "Memes/tomfoolery",
  "Thank you, Joe! You always make us proud because you truly represent Colorado!",
  "Skippy",
  "All hearts, no hesitation.",
  '"How Rich People Fight"',
  "Nandor had a rough go of it",
  "Stolen memes redistributed for the people",
  "When the deer in the headlights jumps over the car.",
  "ICE CANT HIDE",
  "Yeah, thats what you sound like.",
  "Is this the Space Force I've heard about?",
  "Capybara stick twirl",
  "60 MAGA Minutes",
  "Five Years of opening my Dream Project in Yemen",
  "They like to nap when I'm away at work.",
  "Close to the end",
  "The service is Purrfect here",
  "Jackosophy",
  "Kitten gets a shot",
  "A Nice Mushroom Farm.",
  "Rogue (from the X-MEN) - Cosplayed by Songbird",
  "Trump succumbs to the Lee Zeldin Effect and dozes off big time in the Oval Office as the U.S. Environmental Protection Agency Administrator Lee Zeldin takes his turn talking to reporters about coal (6/4/2026)",
  "Important Queer History!",
  "Winning",
  "DoKomi Con recap",
  "It was a Cat-astrophe",
  "Meme dump",
  "I'm so relieved, so grateful, so exhausted. This has been the longest 5 months of my life.",
  "Find yourself a woman who supports you",
  'This is some "righteous dude" stuff. Hunter Biden is doing a public service.',
  "Illegal Delaney Hall ice center",
  "She didn’t see that coming!",
  "How to test for deep fake AI",
  "Thylacine Thursday",
  "Where the hell is my mama?  Why’s it taking her so long to get back to me, me, me?",
  "trumps big lie died",
  "Ice left empty handed",
  "20 nice and wholesome things to brighten your day, vol 277",
  "Enthusiastic woman is enthusiastic",
  "Facts",
  "Utter chaos",
  "Son, will you help me set up an 'Axe Me Anything' on Reddit?",
  "This place needs more Toucans",
  "Shit, another one (con job) I missed.",
  "He put the Staff in Staff Sergeant",
  "Cronch Monch ASMR",
  "All Power Belongs To The People",
  "RIP Marjane Satrapi",
  "Animal Videos",
  "Clever student project",
  "Did you watch this as a kid?  What did you think?",
  "Orange Canary sings a song for you.",
  "this stray dog walked into a vet clinic alone to ask for help... his intelligence is beautiful.",
  "You can't eat the harpies, no matter how delicious they are.",
  "Custumer states...",
  "1 Million New Car Buyers Vanish From U.S. Economy, a New Car Increasingly Becomes a Distant Dream",
  "Start Talking",
  "What’s For Dinner?  80 Vintage Images of People & Food!",
  "This is a good thing. The dems challenges to Trump's abuses of the medical system will move forward.",
  "You took 'cutting the watermelon' to a whole different level.",
  "The artists behind the memes",
  "Every day is a good day with Amira",
  "HAVE YOU NO PRIDE !!!",
  "If they didn’t have double standards they wouldn’t have any standards at all",
  "Day 277 of posting Calvin and Hobbes Comics every day.",
  "Wait a minute.",
  "Meme Redistribution System TM",
  "Drawing Timelapse",
  "Curious minds want to know. Still funny",
  "Capybath",
  "A gal with hobbies",
  "Ain't that a bitch when it happens?",
  "Warhammer 40k - Perplexingly Somehow Still Even More Nemesor Zahndrekh and Lychguard Obyron comics & memes",
  "stop motion animator",
  "Benny's first day of puppy preschool",
  "They're Spraying the Gay",
  "Happy Thursday to everyone born from 1981-1996",
  "Thursday Dump",
  "Children and families are the ones fighting for their rights.",
  "We have let technology run amok without restraint",
  "Tom Cruise got the fame, but they got the disappointment......",
  "repost",
  "Instant scientific FaFo.",
  "Trump attacking reporter: \"I never see a f- smile off her face. So, uh, the reporters should be happy. They shouldn't be unhappy, because you know what we're doing, we're saving our country\" – '80 Year Old Fart Saves Country' by belittling female's looks",
  "There are 2 types of kittens in the world and these girls are perfect examples!!",
  "Wholesome",
  'Monte Mader (@montemader): "Our voices matter"',
  "On that day, Trump will have that large crowd he always wanted.",
  "If you've seen one psychotic dictator...",
  "We're getting him microchipped.",
  "I don't care about politics, said screwworm",
  "Bicurious? More like biFURIOUS",
  "Sombrero Galaxy New DECam Image",
  "Warhammer TOW - Clan Skryre comics & memes",
  "Stephen Miller is an ugly fuck.",
  "Milkshakez Update :)",
  "Ancient action figure",
  "You need more juice guys :)",
  "Tooooooonight we're gonna party like it's 1899!",
  "I Have The Power!",
  "Video Half-Dump #25",
  "Not only does he know how to party, he’s also pretty fucking funny.",
  "Eating my feelings.",
  "Scott The Patriot",
  "Nearly 60 Idahoans sick after drinking raw milk in past two weeks, officials say",
  "Trying to get through the week like...",
  "Patrick Stewart",
  "Xcellently Zesty Voids",
  "Draw Everything June 2026 – Day 4: SunnyRay",
  "The lack of worldly justice is unbearable",
  "Order in chaos.",
  "Knights of Guinevere: Problem (almost) solved",
  "Republicans are awful people. Every single one of them.",
  "The first thing I've learned about God is that he always needs money - George Carlin",
  "FYI bees",
  "the pipeline scout, by huleeb",
  "Starting some traditions: morning cuddles",
  "Learning Curve [OC]",
  "A photo of my pup Tiger Lilly #1258",
  "Three only 3.. To me these are top shelf.",
  '"Sketches" oc',
  "You're a sea-pupper.",
  "For new I came close with the old sandy hook conspiracy videos. They were creative edited to hide their blatant lying. Someone pointed it out to me early. Thankfully I can bite recognize the tricks they use.",
  "Pride",
  "Maverick tha menace is named appropriately",
  "Vote for Dan Sullivan!",
  "DREAM TEAM SUPREME ~ Reset",
  "The game",
  "Looks at you like could you believe this.",
  "LSIW... :)",
  "I love the internet",
  "Makes you think",
  "Give it a little push :)",
  "American Rights",
  "Morning wake up with Shadow and Chance",
  "Meatball lost his meatballs",
  "Marjane Satrapi, creator of Persepolis and acclaimed French-Iranian artist, dies aged 56",
  "Smart and Fit :)",
  "We have a new member of the family",
  "Dumping responsibly",
  "Good news is they're getting along and just being cats. She hisses now and then when he gets too rambunctious but he always backs off.",
  "When defenestrating is not enough, you need spacing.",
  "THT Dancing",
  "A fun dump of fun",
  "Just kidding .....",
  "Henry Cavil and sarcasm.",
  "Return of the Meme: 1707 (cucumber)",
  "A poorly cared for historic artifact, mistaken for another cat ?!, a BMX pump track and a curious but relaxed golden retriever.",
  "DREAM TEAM SUPREME ~ Steel Fists",
  "When she has guns :)",
  "This morning I have been mostly mucking about",
  "Cheesey post",
  "And they wonder where the label came from ....",
  "Brendan Fraser’s reaction ?",
  "My racing Yae Miko cosplay from Genshin Impact :3",
  "Fancy a movie for the weekend?",
  "Wake up.",
  "It's perfect, I loathe it.",
  "Dumps of Unusual Size 272: Artscapes, part two",
  "Ciri (The Witcher 3 cosplay) by Nancy Novikova",
  "A day in the life of a trucker (3 June, 2026)",
  "It's longish but worth the read again (from Nov 2024)",
  "A repost worth seeing",
  "Big boi",
  "GovBrief Today #489",
  "Cloverfield vibes.",
  "The lights in our house are sound-activated. My dad is sleeping downstairs in the living room, and every time he snores, the lights turn on.",
]

export default TITLES
